package com.trn.ns.page.constants;

/**
 * Logs generated by the caching process
 */
public class CachingLogConstants {
	public static final String SET_TOKEN = "worker setToken";
	public static final String INIT_CONFIG_SETTINGS = "worker setToken";
	
	public static final String ADDED_IMAGE_CACHE = "Added image cache for series/viewbox";
	public static final String ADDED_SERIES_INFO = "worker added series info";
	public static final String ADDED_CACHE_CONTEXT = "worker added new context";
	
	public static final String SET_ACTIVE_VIEWBOX = "worker setting active viewbox";

	public static String NO_CACHE_SERIES(String modality) {
		return "addSeriesContext() - cache of series with mime type " + modality + " is not supported.";
	}
	
	public static final String START_ACTIVE_VIEWBOX_CACHE = "worker startCache() --- cache series for active viewbox";
	public static final String START_INACTIVE_VIEWBOX_CACHE = "worker startCache() --- cache series for inactive viewbox";
	public static final String START_NO_DISPLAYING_VIEWBOX_CACHE = "worker startCache() --- cache series for non displaying series";
	
	public static final String CHANGE_ACTIVE_VIEWBOX = "worker made current active as inactive and new cache context active";
	public static final String CLEAR_RETRIEVE_LIST = "worker clearRetrieveInstanceList()";
	
	public static final String IMAGE_FOUND = "RPD/lossy pixel data was found image";
	public static final String IMAGE_NOT_FOUND = "RPD/lossy pixel data was not found image";
	
	public static final String LOSSY_DELETED_OLD_CONTEXT = "Lossy caching: deleted old context";
	
	public static final String OUTPUT_PANEL_NO_LOSSY_CACHING = "Output panel: not caching in lossy rendering mode";
	
	public static String LOSSY_CONTEXT_CHANGED(int viewboxNumber) {
		int index = viewboxNumber - 1;
		return "Lossy caching: Cache context has changed for viewbox: " + index;
	}
	
	public static String LOSSY_CLEARED_CONTEXT(int viewboxNumber) {
		int index = viewboxNumber - 1;
		return "Lossy caching: Cleared old cache for viewbox: " + index;
	}

	
	public static final String CACHE_COMPLETED = "worker marked cache completed";
	
	public static String ALL_CACHE_DONE(int cacheCount) {
		if(cacheCount == -1) {
			return "worker cache all done for";
		}
		return "worker cache all done for " + cacheCount + " series/viewboxes";
	}
}
